[build]
  publish = "public"
  functions = "netlify/functions"
  command = "npm install"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

[[redirects]]
  from = "/booking/*"
  to = "/booking-detail.html"
  status = 200

[[redirects]]
  from = "/admin"
  to = "/admin/index.html"
  status = 200

[[redirects]]
  from = "/select/*"
  to = "/select.html"
  status = 200
