const express = require('express');
const crypto = require('crypto');
const bcrypt = require('bcryptjs');
const jwt = require('jsonwebtoken');
const supabase = require('../supabase');
const { readSettings, writeSettings } = require('../config');
const { todayJakartaStr, toMinutes } = require('../utils/time');
const { getAuthUrl, saveOAuthCode, listDriveImages, syncBookingToCalendar } = require('../google');

const router = express.Router();
const COOKIE_NAME='kaia_admin';
function jwtSecret(){ const s=process.env.ADMIN_JWT_SECRET; if(!s){ if(process.env.NODE_ENV==='production') throw new Error('ADMIN_JWT_SECRET is required in production'); return null; } return s; }
function parseCookies(req){ const out={}; const h=req.headers.cookie||''; h.split(';').forEach(part=>{const i=part.indexOf('=');if(i>=0)out[part.slice(0,i).trim()]=decodeURIComponent(part.slice(i+1).trim());}); return out; }
function setAuthCookie(res,token){ const prod=process.env.NODE_ENV==='production'; res.setHeader('Set-Cookie',`${COOKIE_NAME}=${token}; HttpOnly; Path=/; Max-Age=28800; SameSite=Lax${prod?'; Secure':''}`); }
function clearAuthCookie(res){ const prod=process.env.NODE_ENV==='production'; res.setHeader('Set-Cookie',`${COOKIE_NAME}=; HttpOnly; Path=/; Max-Age=0; SameSite=Lax${prod?'; Secure':''}`); }
function requireAdmin(req,res,next){ try{const secret=jwtSecret(); if(!secret)return res.status(503).json({error:'Admin authentication belum dikonfigurasi.'}); const token=parseCookies(req)[COOKIE_NAME]; if(!token)return res.status(401).json({error:'Silakan login sebagai admin.'}); req.admin=jwt.verify(token,secret); next();}catch(e){if(e.message==='ADMIN_JWT_SECRET is required in production')return res.status(500).json({error:'Server authentication misconfigured.'}); return res.status(401).json({error:'Sesi login sudah tidak valid, silakan login ulang.'});} }

router.post('/login',async(req,res)=>{try{const secret=jwtSecret();if(!secret)return res.status(503).json({error:'Admin authentication belum dikonfigurasi.'});const {email,password}=req.body;const {data:admin}=await supabase.from('admin_users').select('*').eq('email',String(email||'').trim().toLowerCase()).single();if(!admin||!bcrypt.compareSync(password||'',admin.password_hash))return res.status(401).json({error:'Email atau password salah.'});setAuthCookie(res,jwt.sign({email:admin.email,role:admin.role},secret,{expiresIn:'8h'}));res.json({ok:true,email:admin.email});}catch(e){console.error(e);res.status(500).json({error:'Login tidak tersedia.'});}});
router.post('/logout',(req,res)=>{clearAuthCookie(res);res.json({ok:true});});
router.get('/me',(req,res)=>{try{const secret=jwtSecret();if(!secret)return res.json({loggedIn:false});const token=parseCookies(req)[COOKIE_NAME];if(!token)return res.json({loggedIn:false});const p=jwt.verify(token,secret);res.json({loggedIn:true,email:p.email,role:p.role});}catch(e){res.json({loggedIn:false});}});

router.get('/summary',requireAdmin,async(req,res)=>{const today=todayJakartaStr(),d=new Date(`${today}T00:00:00Z`);d.setUTCDate(d.getUTCDate()+6);const weekEnd=d.toISOString().slice(0,10);const [{count:total},{count:todayCount},{count:waitingPayment},{count:paid},{count:thisWeek}]=await Promise.all([
  supabase.from('bookings').select('*',{count:'exact',head:true}),supabase.from('bookings').select('*',{count:'exact',head:true}).eq('booking_date',today),supabase.from('bookings').select('*',{count:'exact',head:true}).eq('payment_status','Unpaid').neq('booking_status','Cancelled'),supabase.from('bookings').select('*',{count:'exact',head:true}).eq('payment_status','Paid'),supabase.from('bookings').select('*',{count:'exact',head:true}).gte('booking_date',today).lte('booking_date',weekEnd)]);res.json({total:total||0,today:todayCount||0,waitingPayment:waitingPayment||0,paid:paid||0,thisWeek:thisWeek||0});});

function safeSearch(v){return String(v||'').trim().replace(/[(),]/g,' ').replace(/[%_]/g,'');}
router.get('/bookings',requireAdmin,async(req,res)=>{let q=supabase.from('bookings').select('*').order('booking_date',{ascending:false}).order('start_time',{ascending:false});const {status,paymentStatus,search,when}=req.query;if(status)q=q.eq('booking_status',status);if(paymentStatus)q=q.eq('payment_status',paymentStatus);if(search){const x=safeSearch(search);if(x)q=q.or(`booking_code.ilike.%${x}%,customer_name.ilike.%${x}%,whatsapp.ilike.%${x}%`);}if(when==='today')q=q.eq('booking_date',todayJakartaStr());if(when==='upcoming')q=q.gte('booking_date',todayJakartaStr());const {data,error}=await q;if(error)return res.status(500).json({error:'Gagal memuat booking.'});res.json(data||[]);});
router.get('/bookings/:id',requireAdmin,async(req,res)=>{const {data:b}=await supabase.from('bookings').select('*,calendar_sync(*)').eq('id',req.params.id).single();if(!b)return res.status(404).json({error:'Booking tidak ditemukan.'});res.json(b);});
router.patch('/bookings/:id',requireAdmin,async(req,res)=>{const {data:b}=await supabase.from('bookings').select('*').eq('id',req.params.id).single();if(!b)return res.status(404).json({error:'Booking tidak ditemukan.'});const {bookingStatus,paymentStatus,notes,cancelReason}=req.body;const allowedBooking=['Pending','Confirmed','Cancelled','Rejected'];const allowedPayment=['Unpaid','Paid'];if(bookingStatus!==undefined&&!allowedBooking.includes(bookingStatus))return res.status(400).json({error:'Status booking tidak valid.'});if(paymentStatus!==undefined&&!allowedPayment.includes(paymentStatus))return res.status(400).json({error:'Status pembayaran tidak valid.'});if(bookingStatus==='Cancelled'&&!String(cancelReason||b.cancel_reason||'').trim())return res.status(400).json({error:'Alasan pembatalan wajib diisi.'});const {error}=await supabase.from('bookings').update({booking_status:bookingStatus||b.booking_status,payment_status:paymentStatus||b.payment_status,notes:notes!==undefined?notes:b.notes,cancel_reason:cancelReason!==undefined?cancelReason:b.cancel_reason,updated_at:new Date().toISOString()}).eq('id',req.params.id);if(error)return res.status(500).json({error:'Gagal menyimpan perubahan.'});res.json({ok:true});});

router.get('/blocked-slots',requireAdmin,async(req,res)=>{let q=supabase.from('blocked_slots').select('*').order('date').order('start_time');if(req.query.date)q=q.eq('date',req.query.date);const {data,error}=await q;if(error)return res.status(500).json({error:'Gagal memuat blocked slot.'});res.json(data||[]);});
router.post('/blocked-slots',requireAdmin,async(req,res)=>{const {date,startTime,endTime,reason}=req.body;if(!date||!startTime||!endTime)return res.status(400).json({error:'Tanggal, jam mulai, dan jam selesai wajib diisi.'});try{if(toMinutes(endTime)<=toMinutes(startTime))return res.status(400).json({error:'Jam selesai harus setelah jam mulai.'});const s=await readSettings();if(toMinutes(startTime)<toMinutes(s.openTime)||toMinutes(endTime)>toMinutes(s.closeTime))return res.status(400).json({error:'Blocked slot harus berada di jam operasional 08:00–18:00 WIB.'});const {data,error}=await supabase.rpc('create_blocked_slot',{p_date:date,p_start:startTime,p_end:endTime,p_reason:reason||''});if(error){if((error.message||'').includes('SLOT_TAKEN'))return res.status(409).json({error:'Slot tersebut bertabrakan dengan booking/blocked slot lain.'});throw error;}res.status(201).json(data);}catch(e){console.error(e);res.status(500).json({error:'Gagal memblokir slot.'});}});
router.delete('/blocked-slots/:id',requireAdmin,async(req,res)=>{const {error}=await supabase.from('blocked_slots').delete().eq('id',req.params.id);if(error)return res.status(500).json({error:'Gagal menghapus blocked slot.'});res.json({ok:true});});

router.get('/packages',requireAdmin,async(req,res)=>{const {data,error}=await supabase.from('packages').select('*').order('category').order('base_price');if(error)return res.status(500).json({error:'Gagal memuat paket.'});res.json(data||[]);});
router.patch('/packages/:id',requireAdmin,async(req,res)=>{const {data:p}=await supabase.from('packages').select('*').eq('id',req.params.id).single();if(!p)return res.status(404).json({error:'Paket tidak ditemukan.'});const body=req.body;const duration=body.durationMinutes===null?null:(body.durationMinutes!==undefined?Number(body.durationMinutes):p.duration_minutes);const {error}=await supabase.from('packages').update({name:body.name??p.name,base_price:body.basePrice??p.base_price,duration_minutes:duration,min_people:body.minPeople??p.min_people,max_people:body.maxPeople!==undefined?body.maxPeople:p.max_people,included_people:body.includedPeople!==undefined?body.includedPeople:p.included_people,additional_person_fee:body.additionalPersonFee!==undefined?body.additionalPersonFee:p.additional_person_fee,active:body.active!==undefined?!!body.active:p.active,updated_at:new Date().toISOString()}).eq('id',req.params.id);if(error)return res.status(500).json({error:'Gagal menyimpan paket.'});res.json({ok:true});});
router.get('/settings',requireAdmin,async(req,res)=>res.json(await readSettings()));
router.patch('/settings',requireAdmin,async(req,res)=>{try{res.json(await writeSettings(req.body));}catch(e){res.status(500).json({error:'Gagal menyimpan settings.'});}});

// Google Calendar OAuth + sync
router.get('/google/oauth/url',requireAdmin,async(req,res)=>{try{res.json({url:await getAuthUrl()});}catch(e){console.error(e);res.status(500).json({error:'Google OAuth belum dapat dimulai.'});}});
router.get('/google/oauth/callback',async(req,res)=>{try{await saveOAuthCode(req.query.code,req.query.state);res.send('<h2>Google berhasil terhubung.</h2><p>Kamu boleh menutup tab ini.</p>');}catch(e){console.error(e);res.status(400).send('Google OAuth gagal atau state sudah tidak valid. Silakan mulai koneksi dari admin lagi.');}});
router.post('/bookings/:id/calendar-sync',requireAdmin,async(req,res)=>{const {data:b}=await supabase.from('bookings').select('*').eq('id',req.params.id).single();if(!b)return res.status(404).json({error:'Booking tidak ditemukan.'});const result=await syncBookingToCalendar(b);res.json(result);});
router.get('/calendar-sync',requireAdmin,async(req,res)=>{const {data,error}=await supabase.from('calendar_sync').select('*,bookings(booking_code,customer_name,booking_date,start_time)');if(error)return res.status(500).json({error:'Gagal memuat status Calendar.'});res.json(data||[]);});

// Drive folder + photo selection
function token(){return crypto.randomBytes(32).toString('base64url');}
function parsePhotoName(name){const m=String(name).match(/^(.+?)[-_](\d+)\.[^.]+$/i);if(m)return {displayName:`${m[1]} - ${m[2]}`,code:m[2]};return {displayName:String(name).replace(/\.[^.]+$/,''),code:null};}
router.post('/bookings/:id/drive-folder',requireAdmin,async(req,res)=>{const {folderId,folderName}=req.body;if(!folderId)return res.status(400).json({error:'folderId wajib diisi.'});try{const photos=await listDriveImages(folderId);const {data,error}=await supabase.from('drive_folders').upsert({booking_id:req.params.id,folder_id:folderId,folder_name:folderName||null,validated_at:new Date().toISOString(),updated_at:new Date().toISOString()},{onConflict:'booking_id'}).select().single();if(error)throw error;res.json({folder: data,photoCount:photos.length});}catch(e){console.error(e);res.status(400).json({error:'Folder Google Drive tidak dapat divalidasi.'});}});
router.post('/bookings/:id/photo-selection',requireAdmin,async(req,res)=>{const {data:b}=await supabase.from('bookings').select('*').eq('id',req.params.id).single();if(!b)return res.status(404).json({error:'Booking tidak ditemukan.'});const {data:folder}=await supabase.from('drive_folders').select('*').eq('booking_id',b.id).single();if(!folder)return res.status(400).json({error:'Hubungkan folder Google Drive terlebih dahulu.'});try{const photos=await listDriveImages(folder.folder_id);const raw=token(),hash=crypto.createHash('sha256').update(raw).digest('hex'),expires=new Date(Date.now()+7*86400000).toISOString();const {data:s,error}=await supabase.from('photo_selection_sessions').insert({booking_id:b.id,token_hash:hash,expires_at:expires,status:'open'}).select().single();if(error)throw error;const rows=photos.map(f=>{const p=parsePhotoName(f.name);return {selection_session_id:s.id,drive_file_id:f.id,file_name:f.name,display_name:p.displayName,code:p.code,mime_type:f.mimeType,thumbnail_url:f.thumbnailLink||null};});if(rows.length){const {error:e}=await supabase.from('photo_metadata').insert(rows);if(e)throw e;}const origin=process.env.PUBLIC_SITE_URL||'';res.status(201).json({url:`${origin}/select/${raw}`,expiresAt:expires,photoCount:rows.length});}catch(e){console.error(e);res.status(500).json({error:'Gagal membuat link pemilihan foto.',detail:e.message});}});
router.get('/bookings/:id/photo-selection',requireAdmin,async(req,res)=>{const {data:s}=await supabase.from('photo_selection_sessions').select('*,photo_selections(*,photo_metadata(*))').eq('booking_id',req.params.id).order('created_at',{ascending:false}).limit(1).maybeSingle();if(!s)return res.json(null);res.json(s);});
router.get('/templates',requireAdmin,async(req,res)=>{const {data,error}=await supabase.from('templates').select('*').order('code');if(error)return res.status(500).json({error:'Gagal memuat template.'});res.json(data||[]);});
router.patch('/templates/:code',requireAdmin,async(req,res)=>{const {status,config}=req.body;if(!['IMPLEMENTED','CONFIGURATION_PENDING','REFERENCE_MISSING'].includes(status||''))return res.status(400).json({error:'Status template tidak valid.'});const {error}=await supabase.from('templates').update({status,config:config||{},updated_at:new Date().toISOString()}).eq('code',req.params.code);if(error)return res.status(500).json({error:'Gagal menyimpan template.'});res.json({ok:true});});
router.get('/bookings/:id/production',requireAdmin,async(req,res)=>{const {data:s}=await supabase.from('photo_selection_sessions').select('template_code,selected_color,photo_selections(position,photo_metadata(display_name,code))').eq('booking_id',req.params.id).eq('status','submitted').order('created_at',{ascending:false}).limit(1).maybeSingle();if(!s)return res.status(404).json({error:'Belum ada selection yang disubmit.'});const photos=(s.photo_selections||[]).sort((a,b)=>a.position-b.position);const list=['Layout '+(s.template_code||''),'',`Warna : Kode (${s.selected_color||''})`,...photos.map((p,i)=>`${i+1}. ${p.photo_metadata?.display_name||'Foto'}`)];res.json({text:list.join('\n'),template:s.template_code,color:s.selected_color,photos});});

module.exports={router,requireAdmin};
